---
- name: Install Jenkins
  become: yes
  gather_facts: No
  hosts: "{{ _hostname }}"
  roles:
    - role: "jenkins"

  # tasks:
  #   - name: Jenkins Install
  #     import_role:
  #       name: jenkins