---
- name: Install Jenkins
  become: yes
  gather_facts: No
  hosts: "{{ _hostname }}"
  roles:
    - role: "Jenkins_Installer"

  # tasks:
  #   - name: Jenkins Install
  #     import_role:
  #       name: jenkins


  handlers:
    - name: Sleep for 30 seconds
      wait_for: timeout=30
      delegate_to: localhost