# - name: Cloning virtual machine from Template "{{ _vmid_template_name }}" with name "{{proxmox_next_vm_id}}-{{ _hostname }}"
#   community.general.proxmox_kvm:
#     api_host: "{{ api_host }}"
#     api_user: "{{ api_user }}"
#     api_password: "{{ api_password }}"
#     node: "{{ node }}"
#     clone: "{{ _vmid_template_name }}"
#     name: "{{ _hostname }}"
#     vmid: "{{ proxmox_next_vm_id }}"
#     storage: externalbay
#     format: raw
#     full: no
#     state: present
#     timeout: 300
#   tags: provission,test

# - name: Configurar recursos da VM
#   community.general.proxmox_kvm:
#     api_host: "{{ api_host }}"
#     api_user: "{{ api_user }}"
#     api_password: "{{ api_password }}"
#     node: "{{ node }}"
#     vmid: "{{ _vmid_template }}"
#     memory: "{{ vm_memory }}"
#     cores: "{{ vm_cores }}"
#     state: present

# - name: Adicionar rede à VM
#   community.general.proxmox_kvm:
#     api_host: "{{ api_host }}"
#     api_user: "{{ api_user }}"
#     api_password: "{{ api_password }}"
#     node: "{{ node }}"
#     vmid: "{{ _vmid_template }}"
#     net:
#       net0: "virtio,bridge=vmbr0"
#     state: present

# - name: Configurar Cloud-Init com IP Estático
#   community.general.proxmox_kvm:
#     api_host: "{{ api_host }}"
#     api_user: "{{ api_user }}"
#     api_password: "{{ api_password }}"
#     node: "{{ node }}"
#     vmid: "{{ _vmid_template }}"
#     ciuser: "admin"
#     cipassword: "senha123"
#     ipconfig:
#       ipconfig0: "ip={{ vm_ip }},gw={{ gateway }}"
#     state: present

# - name: Iniciar a nova VM
#   community.general.proxmox_kvm:
#     api_host: "{{ api_host }}"
#     api_user: "{{ api_user }}"
#     api_password: "{{ api_password }}"
#     node: "{{ node }}"
#     vmid: "{{ _vmid_template }}"
#     state: started

####################################################################################################################################
####################################################################################################################################
####################################################################################################################################

- name: set fact here
  set_fact:
    randome_number: "{{ 100 | random }}"

- name: Cloning virtual machine from Template "{{ _vmid_template }}" with name "{{proxmox_next_vm_id}}-{{ _hostname }}"
  community.general.proxmox_kvm:
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    api_host: "{{ api_host }}"
    # name: "{{ _hostname }}"
    name: "{{ _hostname }}_{{ randome_number }}" ##########################################################
    node: "{{ node }}"
    clone: "{{ _vmid_template }}"
    vmid: "{{ _vmid_template }}"
    newid: "{{ proxmox_next_vm_id }}"
    storage: externalbay
    format: raw
    timeout: 300
  tags: provission,test

- name: Increasing disk ...
  shell: A=$(qm list | grep "{{ _hostname }}" | awk '{print $1}'); B=$(qm list | grep "{{ _hostname }}" | awk '{print $5}'); qm resize $A {{ vm_default_disk }} {{ _disk }}G
  when: '{{ _disk }} != "0"'
  tags: provission

- name: Configuring Memory ...
  shell: A=$(qm list |grep "{{ _hostname }}" | awk '{print $1}'); qm set $A --memory '{{ _memory }}'
  tags: provission

- name: Configuring CPU Cores ...
  shell: A=$(qm list |grep "{{ _hostname }}" | awk '{print $1}'); qm set $A --cores '{{ _cores }}'
  tags: provission

- name: Configuring IP ...
  shell: A=$(qm list |grep "{{ _hostname }}" | awk '{print $1}'); qm set $A --ipconfig0 'ip={{ proxmox_next_vm_ip }}/24,gw={{ proxmox_next_container_gw }}'
  tags: provission

- name: Configuring Description ...
  shell: A=$(qm list |grep "{{ _hostname }}" | awk '{print $1}'); qm set $A --description '<b>{{ _hostname }}:</b><br>- <b>ID:</b> _{{ proxmox_next_vm_id }}_<br>- <b>hostname:</b> _{{ _hostname }}_<br>- <b>IP:</b> _{{ proxmox_next_vm_ip }}_<br>- <b>OS:</b> _{{ vm_default_os }}_<br>- <b>User:</b> _{{ vm_default_user }}_<br>- <b>Password:</b> _{{ vm_default_password }}_'
  tags: provission

- name: Create cloud-init config file ...
  shell: |
    cat << EOF > /var/lib/vz/snippets/cloud_init_conf_{{ proxmox_next_vm_id }}.yml
    #cloud-config
    runcmd:
      - hostnamectl set-hostname {{ _hostname }}
    ssh_pwauth: true
    EOF
  tags: provission

- name: Configuring cloud-init ...
  shell: A=$(qm list |grep "{{ _hostname }}" | awk '{print $1}'); qm set $A --cicustom 'user=local:snippets/cloud_init_conf_{{ proxmox_next_vm_id }}.yml'
  tags: provission

- name: Starting new Virtual Machine in current proxmox node
  community.general.proxmox_kvm:
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    api_host: "{{ api_host }}"
    name: "{{ _hostname }}"
    node: "{{ node }}"
    state: started
    timeout: 60
  tags: provission
  ignore_errors: true

# - name: Waiting 30 Seconds ...
#   ansible.builtin.pause:
#     seconds: 30    

# - name: Change the hostname
#   become: true
#   delegate_to: "{{ proxmox_next_vm_id }}"
#   ansible.builtin.hostname:
#     name: "{{ _hostname }}"

# - name: Set new IP adress
#   delegate_to: "{{ proxmox_next_vm_id }}"
#   ip: "{{ _network_ip }}"
#   interface: ens18




# # - name: Install SSHD
# #   become: true
# #   command: lxc-attach --name {{ _vmid }} -e -- dnf install -y openssh-server
# #   register: install_sshd
# # - debug:
# #     msg: SSHD install status - {{ install_sshd.stdout }}
# #   loop_control:
# #     pause: 2




# - name: Restart machine
#   delegate_to: "{{ proxmox_next_vm_ip }}"
#   reboot: