- name: Stop Container
  community.general.proxmox:
    vmid: "{{ _vmid }}"
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    api_host: "{{ api_host }}"
    force: yes
    state: stopped
  loop_control:
    pause: 5

- name: Destroy container
  community.general.proxmox:
    vmid: "{{ _vmid }}"
    api_user: "{{ api_user }}"
    api_password: "{{ api_password }}"
    api_host: "{{ api_host }}"
    state: absent