---
- name: Get Informations of {{ id }} 
  register: _info
  community.general.proxmox_vm_info:
    api_host: "{{ api_host }}"
    api_user: "{{ api_user }}"
    api_password: "{{ hostvars['proxmox'].ansible_password }}"
    node: "{{ node }}"
    vmid: "{{ id }}"

- set_fact:
    id_type: "{{ _info.proxmox_vms | map(attribute='type') | list | first }}"
    proxmox_vmid_name: "{{ _info.proxmox_vms | map(attribute='name') | list | first }}"

- block:
    - name: Get the IP of qemu {{ id }}
      ansible.builtin.shell: set pipefail && awk -v IGNORECASE=1 '$1 == "ipconfig0:" { print }' /etc/pve/qemu-server/{{ id }}.conf | cut -d'=' -f2 | cut -d'/' -f1
      register: qemu_result_ip
      retries: 10
      delay: 10      
    - set_fact:
        proxmox_vmid_ip: "{{ qemu_result_ip.stdout }}"
  when: id_type == 'qemu'

- block:
    - name: Get the IP of lxc {{ id }}
      ansible.builtin.shell: set pipefail && awk -v IGNORECASE=1 '$1 == "net0:" { print }' /etc/pve/lxc/{{ id }}.conf | cut -d',' -f5 | cut -d'=' -f2 | cut -d'/' -f1
      register: lxc_result_ip
      retries: 10
      delay: 10
    - set_fact:
        proxmox_vmid_ip: "{{ lxc_result_ip.stdout }}"
  when: id_type == 'lxc'

- debug: 
    msg: "Type:{{ id_type }} <> Id:{{ id }} <> Name:[{{ proxmox_vmid_name }}] <> Ip:{{ proxmox_vmid_ip }}"