- name: Get IP for vmid/ctid {{ id }}
  # delegate_to: proxmox
  ansible.builtin.shell: set pipefail && awk -v IGNORECASE=1 '$1 == "net0:" { print }' /etc/pve/lxc/{{ id }}.conf | cut -d',' -f5 | cut -d'=' -f2 | cut -d'/' -f1
  register: result_ip
  retries: 10
  delay: 10

- name: Get Hostname for vmid/ctid {{ id }}
  # delegate_to: proxmox
  ansible.builtin.shell: set pipefail && awk -v IGNORECASE=1 '$1 == "hostname:" { print }' /etc/pve/lxc/{{ id }}.conf | cut -d':' -f2 | xargs
  register: result_hostname
  retries: 10
  delay: 10