---
- name: Get all existing Containers in Proxmox
  register: all_ct
  community.general.proxmox_vm_info:
    api_host: pimentel-homelab
    api_user: root@pam
    node: pimentel-homelab
    api_password: "{{ hostvars['proxmox'].ansible_password }}"
    type: lxc

- name: Last Container in Proxmox
  debug: msg="{{ all_ct.proxmox_vms | last }}"

- set_fact:
    last_container_name: "{{ all_ct.proxmox_vms | map(attribute='name') | list | last }}"
    last_container_id: "{{ all_ct.proxmox_vms | map(attribute='vmid') | list | last }}"