---
- name: Get all existing Virtual Machines in Proxmox
  register: all_vm
  community.general.proxmox_vm_info:
    api_host: pimentel-homelab
    api_user: root@pam
    node: pimentel-homelab
    api_password: "{{ hostvars['proxmox'].ansible_password }}"
    type: qemu

- name: Get all existing Containers in Proxmox
  register: all_ct
  community.general.proxmox_vm_info:
    api_host: pimentel-homelab
    api_user: root@pam
    node: pimentel-homelab
    api_password: "{{ hostvars['proxmox'].ansible_password }}"
    type: lxc

- set_fact:
    last_vm_name: "{{ all_vm.proxmox_vms | map(attribute='name') | list | last }}"
    last_vm_id: "{{ all_vm.proxmox_vms | map(attribute='vmid') | list | last }}"
    last_container_name: "{{ all_ct.proxmox_vms | map(attribute='name') | list | last }}"
    last_container_id: "{{ all_ct.proxmox_vms | map(attribute='vmid') | list | last }}"

# - name: Last Virtual Machine and Container in Proxmox
- debug: 
    msg: 
      - "Last Virtual Machine: Id:{{ last_vm_id }} <> Name:{{ last_vm_name }}"
      - "Last Container Id:{{ last_container_id }} <> Name:{{ last_container_name }}"

