- debug:
    msg: 
      - "AAAAAAAAAAAAA={{ host }}"
      - "BBBBBBBBBBB={{ hostvars[host].ansible_host }}"
      - "DDDDDDDDDDDDD={{ external_call_host }}"

- set_fact:
    host: "{{ external_call_host }}"
  when: external_call_host is defined
  
- debug:
    msg: 
      - "AAAAAAAAAAAAA 22222={{ host }}"

- name: Create host in inventory {{ inventory }}
  awx.awx.host:
    name: "{{ _hostname }}"
    description: "{{ _description }}"
    inventory: "{{ inventory }}"
    state: present
    enabled: true
    controller_host: "http://{{ hostvars[host].ansible_host }}"
    controller_oauthtoken: "{{ awx_token }}"
    validate_certs: false
    variables:
      ansible_host: "{{ _network_ip }}"