- set_fact:
    _controller_host: "http://{{ hostvars[external_call_host].ansible_host }}"
  when: external_call_host is defined
- set_fact:
    _controller_host: "http://{{ hostvars[host].ansible_host }}"
  when: external_call_host is undefined

- name: Create host in inventory {{ inventory }}
  awx.awx.host:
    name: "{{ _hostname }}"
    description: "{{ _description }}"
    inventory: "{{ inventory }}"
    state: present
    enabled: true
    controller_host: "{{ _controller_host }}"
    controller_oauthtoken: "{{ awx_token }}"
    validate_certs: false
    variables:
      ansible_host: "{{ _network_ip }}"