- debug: 
    msg: 
      - "_vm_default_user: {{ _vm_default_user }}"
      - "_vm_default_password: {{ _vm_default_password }}"




- set_fact:
    _controller_host: "http://{{ hostvars[external_call_host].ansible_host }}"
  when: external_call_host is defined
- set_fact:
    _controller_host: "http://{{ hostvars[host].ansible_host }}"
  when: external_call_host is undefined

- name: Create host in inventory {{ inventory }}
  awx.awx.host:
    # name: "{{ _hostname }}"
    name: "{{ _hostname }}--tt-rr" ####################################################################
    description: "{{ _description }}"
    inventory: "{{ inventory }}"
    state: present
    enabled: true
    controller_host: "{{ _controller_host }}"
    controller_oauthtoken: "{{ awx_token }}"
    validate_certs: false
    variables:
      ansible_host: "{{ _network_ip }}"
      ansible_user: "{{ _vm_default_user }}" 
      ansible_password: "{{ _vm_default_password }}"
    # variables: >
    #   {
    #     "ansible_host": "{{ _network_ip }}",
    #     {% if _vm_default_user is defined and _vm_default_user | length > 0 %}
    #     "ansible_user": "{{ _vm_default_user }}",
    #     {% endif %}
    #     {% if _vm_default_password is defined and _vm_default_password | length > 0 %}
    #     "ansible_password": "{{ _vm_default_password }}"
    #     {% endif %}
    #   }