# - name: Delete host from inventory {{ inventory }}
#   awx.awx.host:
#     name: "{{ _hostname }}"
#     inventory: "{{ inventory }}"
#     state: absent
#     controller_host: "http://{{ controller_host }}"
#     controller_oauthtoken: "{{ awx_token }}"
#     validate_certs: false

- name: Get running jobs for host {{ _hostname }}
  awx.awx.job_list:
    controller_host: "http://{{ controller_host }}"
    controller_oauthtoken: "{{ awx_token }}"
    query:
      host__name: "{{ _hostname }}"
      status__in: ["running", "pending"]
  register: running_jobs

- name: Debug job list output
  debug:
    var: running_jobs

- name: Ensure all running jobs are canceled
  awx.awx.job_cancel:
    job_id: "{{ item.id }}"
    controller_host: "http://{{ controller_host }}"
    controller_oauthtoken: "{{ awx_token }}"
  loop: "{{ running_jobs.jobs | default([]) }}"
  ignore_errors: true
  register: canceled_jobs
  until: canceled_jobs.failed == 0
  retries: 5
  delay: 10
  when: running_jobs.jobs | default([]) | length > 0

- name: Wait for jobs to be canceled
  pause:
    seconds: 10
  when: running_jobs.jobs | default([]) | length > 0

- name: Debug before deleting host
  debug:
    msg: "Attempting to delete host {{ _hostname }} from inventory {{ inventory }}"

- name: Delete host from inventory {{ inventory }}
  awx.awx.host:
    name: "{{ _hostname }}"
    inventory: "{{ inventory }}"
    state: absent
    controller_host: "http://{{ controller_host }}"
    controller_oauthtoken: "{{ awx_token }}"
    validate_certs: false
