# - name: Delete host from inventory {{ inventory }}
#   awx.awx.host:
#     name: "{{ _hostname }}"
#     inventory: "{{ inventory }}"
#     state: absent
#     controller_host: "http://{{ controller_host }}"
#     controller_oauthtoken: "{{ awx_token }}"
#     validate_certs: false


- name: Get inventory ID by name
  awx.awx.inventory:
    name: "{{ inventory }}"
    organization: "pimentel-org"  # Adicionando organização
    controller_host: "http://{{ controller_host }}"
    controller_oauthtoken: "{{ awx_token }}"
    validate_certs: false
  register: inventory_data


- name: Debug inventory data
  debug:
    var: inventory_data

- name: Set inventory ID fact
  set_fact:
    inventory_id: "{{ inventory_data.id }}"

- name: Get running jobs for inventory {{ inventory }}
  awx.awx.job_list:
    controller_host: "http://{{ controller_host }}"
    controller_oauthtoken: "{{ awx_token }}"
    query:
      status__in: ["running", "pending"]
      inventory: "{{ inventory_id }}"
  register: running_jobs

- name: Debug job list output
  debug:
    var: running_jobs

- name: Extract job IDs
  set_fact:
    jobs_to_cancel: "{{ running_jobs.results | map(attribute='id') | list }}"

- name: Cancel running jobs
  awx.awx.job_cancel:
    job_id: "{{ item }}"
    controller_host: "http://{{ controller_host }}"
    controller_oauthtoken: "{{ awx_token }}"
  loop: "{{ jobs_to_cancel }}"
  ignore_errors: true
  when: jobs_to_cancel | length > 0

- name: Delete host from inventory {{ inventory }}
  awx.awx.host:
    name: "{{ _hostname }}"
    inventory: "{{ inventory_id }}"
    state: absent
    controller_host: "http://{{ controller_host }}"
    controller_oauthtoken: "{{ awx_token }}"
    validate_certs: false
  register: delete_host_result
  retries: 3
  delay: 5
  until: delete_host_result.failed is not defined or delete_host_result.failed == false
