# - name: Delete host from inventory {{ inventory }}
#   awx.awx.host:
#     name: "{{ _hostname }}"
#     inventory: "{{ inventory }}"
#     state: absent
#     controller_host: "http://{{ controller_host }}"
#     controller_oauthtoken: "{{ awx_token }}"
#     validate_certs: false



- name: Get running jobs for inventory {{ inventory }}
  awx.awx.job_list:
    controller_host: "http://{{ controller_host }}"
    controller_oauthtoken: "{{ awx_token }}"
    query:
      status__in: ["running", "pending"]
      inventory: "{{ inventory }}"
  register: running_jobs

- name: Debug job list output
  debug:
    var: running_jobs

- name: Extract job IDs
  set_fact:
    jobs_to_cancel: "{{ running_jobs.results | map(attribute='id') | list }}"

- name: Debug extracted job IDs
  debug:
    var: jobs_to_cancel

# - name: Cancel running jobs
#   awx.awx.job_cancel:
#     job_id: "{{ item }}"
#     controller_host: "http://{{ controller_host }}"
#     controller_oauthtoken: "{{ awx_token }}"
#   loop: "{{ jobs_to_cancel }}"
#   ignore_errors: true
#   when: jobs_to_cancel | length > 0

# - name: Wait for jobs to be canceled
#   pause:
#     seconds: 10
#   when: jobs_to_cancel | length > 0

# - name: Delete host from inventory {{ inventory }}
#   awx.awx.host:
#     name: "{{ _hostname }}"
#     inventory: "{{ inventory }}"
#     state: absent
#     controller_host: "http://{{ controller_host }}"
#     controller_oauthtoken: "{{ awx_token }}"
#     validate_certs: false
#   register: delete_host_result
#   retries: 3
#   delay: 5
#   until: delete_host_result is not failed
