# - name: Delete host from inventory {{ inventory }}
#   awx.awx.host:
#     name: "{{ _hostname }}"
#     inventory: "{{ inventory }}"
#     state: absent
#     controller_host: "http://{{ controller_host }}"
#     controller_oauthtoken: "{{ awx_token }}"
#     validate_certs: false

- name: Cancel running jobs for host {{ _hostname }}
  awx.awx.job_list:
    controller_host: "http://{{ controller_host }}"
    controller_oauthtoken: "{{ awx_token }}"
    job_events: true
  register: running_jobs

- name: Debug running jobs
  debug:
    var: running_jobs

- name: Stop running jobs
  awx.awx.job_cancel:
    job_id: "{{ item.id }}"
    controller_host: "http://{{ controller_host }}"
    controller_oauthtoken: "{{ awx_token }}"
  loop: "{{ running_jobs.results }}"
  when: item.status in ['running', 'pending']
  ignore_errors: true

- name: Debug stopped jobs
  debug:
    msg: "Job {{ item.id }} status: {{ item.status }}"
  with_items: "{{ running_jobs.results }}"
  when: item.status in ['running', 'pending']

- name: Wait for jobs to be canceled
  pause:
    seconds: 10

- name: Delete host from inventory {{ inventory }}
  awx.awx.host:
    name: "{{ _hostname }}"
    inventory: "{{ inventory }}"
    state: absent
    controller_host: "http://{{ controller_host }}"
    controller_oauthtoken: "{{ awx_token }}"
    validate_certs: false

- name: Debug host deletion
  debug:
    msg: "Host {{ _hostname }} deleted from inventory {{ inventory }}"
