- name: Get IP for vmid/ctid {{ _id }}
  delegate_to: proxmox
  ansible.builtin.shell: set pipefail && awk -v IGNORECASE=1 '$1 == "net0:" { print }' /etc/pve/lxc/{{ _id }}.conf | cut -d',' -f5 | cut -d'=' -f2 | cut -d'/' -f1
  register: result_ip
  retries: 10
  delay: 10

- name: Get Hostname for vmid/ctid {{ _id }}
  delegate_to: proxmox
  ansible.builtin.shell: set pipefail && awk -v IGNORECASE=1 '$1 == "hostname:" { print }' /etc/pve/lxc/{{ _id }}.conf | cut -d':' -f2 | xargs
  register: result_hostname
  retries: 10
  delay: 10

- name: Collect AWX root token
  command: docker exec awx_task /bin/bash -c 'awx-manage create_oauth2_token --user root'
  register: awx_token