version: "3"

services:
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    ports:
      - 8081:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    restart: unless-stopped
    networks:
        - tools

networks:
    tools:
        name: tools