---
- name: Remove Java Packages if they exist
  package:
    name: "{{ item }}"
    state: absent
  loop:
    - java

- name: Installing Java required packages
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - java-11-openjdk
    - java-11-openjdk-devel

- name: Download jenkins.repo
  get_url:
    url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins Key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat/jenkins.io-2023.key

- name: Install Jenkins
  package:
    name: jenkins
    state: latest

- name: Start Jenkins Service
  service:
    name: jenkins
    state: started
    enabled: yes

- name: Sleep for 30 seconds and continue with play ...
  wait_for: timeout=30
  delegate_to: localhost

- name: Get Init Admin Password
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  changed_when: false
  register: adminPasswordResult

- name: Print init password jenkins
  debug:
    var: adminPasswordResult.stdout