---
- name: Wait for Jenkins to start up
  uri:
    url: http://{{ hostvars[host].ansible_host }}:{{ jenkins_port }}/login?from=%2F
    status_code: 200
    timeout: 5
  register: jenkins_service_status
  # Keep trying for 5 mins in 5 sec intervals
  retries: 10
  delay: 5
  until: >
     'status' in jenkins_service_status and
     jenkins_service_status['status'] == 200

- name: Install Plugins
  jenkins_plugin:
    name: "{{ item }}"
    url_username: admin
    url_password: "{{ adminPasswordResult.stdout }}"
  with_items: 
    - "{{ jenkins_default_plugins }}"
    - "{{ jenkins_custom_plugins }}"
  notify: Restart Jenkins Service

- meta: flush_handlers