---
- name: Installing Java-11
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - java-11-openjdk
    - java-11-openjdk-devel

- name: Sleep for 10 seconds and continue with play ...
  wait_for: timeout=10
  delegate_to: localhost

- name: "Check if Java installed properly"
  shell: java -version
  register: javaversion

- fail:
      msg: "Java should have been installed by now"
  when: javaversion.rc == 127