---
- name: Installing Java-11
  package:
    name: "{{ item }}"
    state: latest
  with_items: 
    - "{{ java_packages }}"
    
- name: "Check if Java installed properly"
  shell: java -version
  register: javaversion

- fail:
      msg: "Java should have been installed by now"
  when: javaversion.rc == 127