version: '3.7'

services:
    jenkins:
        build:
            context: "."
            dockerfile: Dockerfile
        image: jenkins:0.0.1
        container_name: jenkins
        restart: always
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - jenkins:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
        privileged: true
        networks:
            - tools

volumes:
    jenkins:
        name: jenkins

networks:
    tools:
        name: tools