---
- name: Destroy the Container with VMID {{ _vmid }}
  become: true
  become_method: sudo
  gather_facts: true
  hosts: "{{ host }}"  
  roles:
    - role: common
        
  tasks:
    - include_role:
        name: proxmox
        tasks_from: "destroy_container.yml"