---
- name: Destroy the Proxmox LXC Container
  become: true
  become_method: sudo
  gather_facts: true
  hosts: "{{ host }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
  # collections:
  #   - awx.awx
  roles:
    - role: proxmox