---
- name: Destroy the Proxmox LXC Container
  become: true
  become_method: sudo
  gather_facts: true
  hosts: "{{ host }}"
  roles:
    - role: common
    
  tasks:
    - include_role:
        name: proxmox
        tasks_from: "destroy_container.yml"