---
- name: Destroy the Proxmox LXC Container
  become: true
  become_method: sudo
  gather_facts: true
  # hosts: "{{ host }}"
  hosts: proxmox
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: proxmox
    # - role: awx
    #   vars:
    #     host: ct-awx
    #     inventory: pimentel-inventory
    #     id: 204
    #     awx_execution_mode: "disable_host"
