---
- name: Configure SSHD in container [{{ _vmid }}] in Proxmox
  become: yes
  gather_facts: No
  hosts: "{{ host }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Install SSHD
      command: |
        lxc-attach --name {{ _vmid }} -e -- dnf install -y openssh-server
      register: install_sshd
    - debug:
        msg: SSHD install status - {{ install_sshd.stdout }}
      loop_control:
        pause: 2

    - name: Start SSHD
      command: |
        lxc-attach --name {{ _vmid }} -e -- systemctl start sshd
      register: start_sshd
    - debug:
        msg: SSHD start status - {{ start_sshd.stdout }}
      loop_control:
        pause: 2

    - name: Enable SSHD
      command: |
        lxc-attach --name {{ _vmid }} -e -- systemctl enable sshd
      register: enable_sshd
    - debug:
        msg: SSHD enable status - {{ enable_sshd.stdout }}
      loop_control:
        pause: 2
