---
- name: Destroy the Container with VMID {{ _vmid }} in the proxmox {{ _api_host }}
  become: yes
  gather_facts: No
  hosts: "{{ host }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Stop Container
      proxmox:
        vmid: "{{ _vmid }}"
        api_user: "{{ _api_user }}"
        api_password: "{{ hostvars[host].ansible_password }}"
        api_host: "{{ _api_host }}"
        force: yes
        state: stopped
      loop_control:
        pause: 5

    - name: Get IP for "{{ _vmid }}"
      ansible.builtin.shell: set pipefail && awk -v IGNORECASE=1 '$1 == "net0:" { print }' /etc/pve/lxc/{{ _vmid }}.conf | cut -d',' -f5 | cut -d'=' -f2 | cut -d'/' -f1
      register: result_ip
      retries: 10
      delay: 10

    - name: Delete host in known_hosts file
      delegate_to: ct-awx
      command: |
        hostname
        pwd
        docker exec awx_task /bin/bash -c 'sed -i "/{{ result_ip.stdout }}/d" /root/.ssh/known_hosts'
      retries: 10
      delay: 10

    - name: Destroy container
      proxmox:
        vmid: "{{ _vmid }}"
        api_user: "{{ _api_user }}"
        api_password: "{{ hostvars[host].ansible_password }}"
        api_host: "{{ _api_host }}"
        state: absent
    
