---
- name: Initial Settings in Virtual Machine create from Template
  become: yes
  gather_facts: No
  hosts: "{{ host }}"
  # vars:
  #   ansible_python_interpreter: /usr/bin/python3
  collections:
    - community.general

  tasks:
    - name: Change the hostname
      become: true
      hostname:
        name: "{{ _hostname }}"

    - name: Restart machine
      command: shutdown -r now "Ansible updates triggered"
      async: 0
      poll: 0
      ignore_errors: True
      when: reboot is defined

    - name: Validate ansible_fqdn == inventory_hostname
      tags:
        - validate
      assert:
        that: ansible_fqdn == inventory_hostname
