---
- name: Initial Settings in Virtual Machine create from Template
  become: yes
  gather_facts: No
  hosts: "{{ host }}"
  # vars:
  #   ansible_python_interpreter: /usr/bin/python3
  collections:
    - community.general

  tasks:
    - name: Change the hostname
      become: true
      hostname:
        name: "{{ _hostname }}"

    - name: Set new IP adress
        ip: "{{ _network_ip }}"
        interface: ens18

    - name: Restart machine
      reboot:
