---
- name: Initial Settings in Virtual Machine create from Template
  become: yes
  gather_facts: No
  hosts: "{{ host }}"
  # vars:
  #   ansible_python_interpreter: /usr/bin/python3
  collections:
    - community.general

  tasks:
    - name: Change the hostname
      become: true
      hostname:
        name: "{{ _hostname }}"

    - name: Restart machine
      command: shutdown -r now "Ansible updates triggered"
      async: 0
      poll: 0
      ignore_errors: True
      when: reboot is defined
    loop_control:
        pause: 10

    # - name: Waiting for server to come back up
    #   local_action: wait_for host="{{ _hostname }}" port=22 state=started

    - name: Fix /etc/hosts removing the old hostname
      tags:
        - hosts
      lineinfile: state=present
        dest=/etc/hosts
        line="{{ ansible_default_ipv4.address }} {{ _hostname }} {{ ansible_hostname }}"
        regexp="^{{ ansible_default_ipv4.address }}"
      when: ansible_fqdn != inventory_hostname

    - name: Validate ansible_fqdn == inventory_hostname
      tags:
        - validate
      assert:
        that: ansible_fqdn == inventory_hostname
