---
- name: Create new Virtual Machine in Proxmox [{{ _node }}] from Template
  become: yes
  gather_facts: No
  hosts: "{{ host }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
  collections:
    - community.general

  tasks:
    - name: Cloning virtual machine from Template "{{ _vmid_template }}" with name "{{ _hostname }}"
      proxmox_kvm:
        api_user: "{{ _api_user }}"
        api_password: "{{ hostvars[host].ansible_password }}"
        api_host: "{{ _api_host }}"
        name: "{{ _hostname }}"
        node: "{{ _node }}"
        clone: "{{ _vmid_template }}"
        vmid: "{{ _vmid_template }}"
        newid: "{{ _vmid }}"
        storage: local-lvm
        format: raw
        timeout: 300
      tags: provission,test

    - name: Increasing disk if it is necessary
      shell: A=$(qm list | grep "{{ _hostname }}" | awk '{print $1}'); B=$(qm list | grep "{{ _hostname }}" | awk '{print $5}'); qm resize $A {{ _default_disk }} {{ _disk }}G
      when: '{{ _disk }} != "0"'
      tags: provission

    - name: Loading set up for Virtual Machine. Assigning IP, sockets, cores, memory and description for Virtual Machine
      shell: A=$(qm list |grep "{{ _hostname }}" | awk '{print $1}'); qm set $A --ipconfig0 'ip={{ _network_ip }}/24,gw={{ _network_gw }}' --memory '{{ _memory }}' --cores '{{ _cores }}' --description '## <b>{{ _hostname }}:</b><br>- <b>ID:</b> _{{ _vmid }}_<br>- <b>hostname:</b> _{{ _hostname }}_<br>- <b>IP:</b> _{{ _network_ip }}_<br>- <b>OS:</b> _x_'
      when: '"{{ _network_ip }}" != "automatic"'
      tags: provission

    - name: Starting new Virtual Machine in current proxmox node
      proxmox_kvm:
        api_user: "{{ _api_user }}"
        api_password: "{{ hostvars[host].ansible_password }}"
        api_host: "{{ _api_host }}"
        name: "{{ _hostname }}"
        node: "{{ _node }}"
        state: started
        timeout: 300
      tags: provission
