---
- name: Create new Virtual Machine in Proxmox [{{ _node }}] from Template
  become: yes
  gather_facts: No
  hosts: "{{ host }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
  collections:
    - community.general

  tasks:
    - name: Cloning virtual machine from Template "{{ _vmid_template }}" with name "{{ _hostname }}"
      proxmox_kvm:
        api_user: "{{ _api_user }}"
        api_password: "{{ hostvars[host].ansible_password }}"
        api_host: "{{ _api_host }}"
        name: "{{ _hostname }}"
        node: "{{ _node }}"
        clone: "{{ _vmid_template }}"
        vmid: "{{ _vmid_template }}"
        newid: "{{ _vmid }}"
        storage: local-lvm
        format: raw
        timeout: 300
      tags: provission,test

    - name: Increasing disk ...
      shell: A=$(qm list | grep "{{ _hostname }}" | awk '{print $1}'); B=$(qm list | grep "{{ _hostname }}" | awk '{print $5}'); qm resize $A {{ _default_disk }} {{ _disk }}G
      when: '{{ _disk }} != "0"'
      tags: provission

    # - name: Loading set up for Virtual Machine. Assigning IP, sockets, cores, memory and description for Virtual Machine
    #   shell: A=$(qm list |grep "{{ _hostname }}" | awk '{print $1}'); qm set $A --ipconfig0 'ip={{ _network_ip }}/24,gw={{ _network_gw }}' --memory '{{ _memory }}' --cores '{{ _cores }}' --description '<b>{{ _hostname }}:</b><br>- <b>ID:</b> _{{ _vmid }}_<br>- <b>hostname:</b> _{{ _hostname }}_<br>- <b>IP:</b> _{{ _network_ip }}_<br>- <b>OS:</b> _x_'
    #   when: '"{{ _network_ip }}" != "automatic"'
    #   tags: provission

    - name: Configuring Memory ...
      shell: A=$(qm list |grep "{{ _hostname }}" | awk '{print $1}'); qm set $A --memory '{{ _memory }}'
      tags: provission

    - name: Configuring CPU Cores ...
      shell: A=$(qm list |grep "{{ _hostname }}" | awk '{print $1}'); qm set $A --cores '{{ _cores }}'
      tags: provission

    - name: Configuring IP ...
      shell: A=$(qm list |grep "{{ _hostname }}" | awk '{print $1}'); qm set $A --ipconfig0 'ip={{ _network_ip }}/24,gw={{ _network_gw }}'
      tags: provission

    - name: Configuring ssh-key ...
      shell: A=$(qm list |grep "{{ _hostname }}" | awk '{print $1}'); qm set $A --sshkey ~/.ssh/id_rsa.pub
      tags: provission

    - name: Configuring Description ...
      shell: A=$(qm list |grep "{{ _hostname }}" | awk '{print $1}'); qm set $A --description '<b>{{ _hostname }}:</b><br>- <b>ID:</b> _{{ _vmid }}_<br>- <b>hostname:</b> _{{ _hostname }}_<br>- <b>IP:</b> _{{ _network_ip }}_<br>- <b>OS:</b> _x_'
      tags: provission

    - name: Create File ...
      shell: |
        cat << EOF > /var/lib/vz/snippets/conf-ssh.yaml
          #cloud-config        
          ssh_pwauth: True ## This line enables ssh password authentication
        EOF
      tags: provission

    - name: ls -lah ...
      shell: ls -lah
      tags: provission

    - name: ls -lah /var/lib/vz/snippets/ ...
      shell: ls -lah /var/lib/vz/snippets/
      tags: provission

    - name: Configuring SSH ...
      shell: A=$(qm list |grep "{{ _hostname }}" | awk '{print $1}'); qm set $A --cicustom "user=local:snippets/conf-ssh.yaml"
      tags: provission

    # - name: XXXXXXXXXXXX ...
    #   shell: ssh cloud-user@{{ _network_ip }}
    #   tags: provission

    - name: Starting new Virtual Machine in current proxmox node
      proxmox_kvm:
        api_user: "{{ _api_user }}"
        api_password: "{{ hostvars[host].ansible_password }}"
        api_host: "{{ _api_host }}"
        name: "{{ _hostname }}"
        node: "{{ _node }}"
        state: started
        timeout: 90
      tags: provission
