---
- name: Install SSHD
  become: true
  command: lxc-attach --name {{ _vmid }} -e -- dnf install -y openssh-server
  register: install_sshd
- debug:
    msg: SSHD install status - {{ install_sshd.stdout }}
  loop_control:
    pause: 2

- name: Start SSHD
  command: lxc-attach --name {{ _vmid }} -e -- systemctl start sshd
  loop_control:
    pause: 2

- name: Enable SSHD
  command: lxc-attach --name {{ _vmid }} -e -- systemctl enable sshd
  loop_control:
    pause: 2

- name: Status SSHD
  command: lxc-attach --name {{ _vmid }} -e -- systemctl status sshd
  register: status_sshd
- debug:
    msg: SSHD status - {{ status_sshd.stdout }}




- name: Configurar sshd_config para permitir root login no LXC
  become: true
  command: lxc-attach --name {{ _vmid }} -e -- sed -i 's/^#\?\(PermitRootLogin\).*/\1 yes/' /etc/ssh/sshd_config

- name: Configurar sshd_config para permitir autenticação por senha
  become: true
  command: lxc-attach --name {{ _vmid }} -e -- sed -i 's/^#\?\(PasswordAuthentication\).*/\1 yes/' /etc/ssh/sshd_config

- name: Reiniciar serviço SSH dentro do LXC
  become: true
  command: lxc-attach --name {{ _vmid }} -e -- systemctl restart sshd
  register: restart_ssh
  delay: 5

- debug:
    msg: "Status da reinicialização do SSH - {{ restart_ssh.stdout }}"
