---

- name: Run a complex command within a "running" container
  community.general.lxc_container:
    name: "{{ _hostname }}"
    container_command: |
      dnf install -y openssh-server


# - name: Install SSHD
#   command: lxc-attach --name {{ _vmid }} -e -- dnf install -y openssh-server
#   register: install_sshd
# - debug:
#     msg: SSHD install status - {{ install_sshd.stdout }}
#   loop_control:
#     pause: 2

- name: Start SSHD
  command: lxc-attach --name {{ _vmid }} -e -- systemctl start sshd
  loop_control:
    pause: 2

- name: Enable SSHD
  command: lxc-attach --name {{ _vmid }} -e -- systemctl enable sshd
  loop_control:
    pause: 2

- name: Status SSHD
  command: lxc-attach --name {{ _vmid }} -e -- systemctl status sshd
  register: status_sshd
- debug:
    msg: SSHD status - {{ status_sshd.stdout }}