---

- name: Family
  debug: msg="{{ ansible_os_family }}"

- name: Distribution
  debug: msg="{{ ansible_distribution }}"

- name: Distribution version
  debug: msg="{{ ansible_distribution_version}}"

- name: Distribution release
  debug: msg="{{ ansible_distribution_release}}"

- name: Distribution major version
  debug: msg="{{ ansible_distribution_major_version }}"





  

- name: Install SSHD
  command: lxc-attach --name {{ _vmid }} -e -- dnf install -y openssh-server
  register: install_sshd
- debug:
    msg: SSHD install status - {{ install_sshd.stdout }}
  loop_control:
    pause: 2

- name: Start SSHD
  command: lxc-attach --name {{ _vmid }} -e -- systemctl start sshd
  loop_control:
    pause: 2

- name: Enable SSHD
  command: lxc-attach --name {{ _vmid }} -e -- systemctl enable sshd
  loop_control:
    pause: 2

- name: Status SSHD
  command: lxc-attach --name {{ _vmid }} -e -- systemctl status sshd
  register: status_sshd
- debug:
    msg: SSHD status - {{ status_sshd.stdout }}