api_host: pimentel-homelab
api_user: root@pam
node: pimentel-homelab
container_root_password: "12345"
unprivileged: true
onboot: false
nesting: 1
keyctl: 1
packages_dependencies_create_container:
  - python3
  - python3-pip