api_host: jabuti
api_user: root@pam
api_password: "@toor@"
node: jabuti
container_root_password: "12345"
unprivileged: true
onboot: false
nesting: 1
keyctl: 1

vm_default_disk: scsi0
vm_default_user: root
vm_default_password: toor

packages_dependencies_create_container:
  - python3
  - python3-pip