---
- name: "Check if java present"
  shell: java -version
  register: javaversion
  failed_when: false

- name: Remove Java old Packages if they exist
  package:
    name: "java"
    state: absent
  when: javaversion.rc == 0

- name: Installing Java-11
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - java-11-openjdk
    - java-11-openjdk-devel
  notify:
  - Sleep for 30 seconds

# - name: Sleep for 30 seconds and continue with play ...
#   wait_for: timeout=30
#   delegate_to: localhost





- name: Fetch Java version
  shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
  register: java_version

- name: Print Java version
  debug:
    var: java_version

- assert:
    that: 
      - java_version.stdout | version_compare('1.7', '>=') 