---
- name: Wait for Jenkins to start up
  uri:
    url: http://192.168.99.21:8080
    status_code: 200
    timeout: 5
  register: jenkins_service_status
  # Keep trying for 5 mins in 5 sec intervals
  retries: 60
  delay: 5
  until: >
     'status' in jenkins_service_status and
     jenkins_service_status['status'] == 200

- name: Install Plugins
  jenkins_plugin:
    name: "{{ item }}"
    # state: latest
    # url_username: admin
    # url_password: "{{ adminPasswordResult.stdout }}"
  with_items: 
    - script-security
    - command-launcher
    - blueocean

- name: Restart Jenkins Service
  service:
    name: jenkins
    state: restarted

- name: Sleep for 30 seconds and continue with play ...
  wait_for: timeout=30
  delegate_to: localhost