---
# - name: Get Init Admin Password
#   shell: cat /var/lib/jenkins/secrets/initialAdminPassword
#   changed_when: false
#   register: adminPasswordResult

# - name: Print init password jenkins
#   debug:
#     var: adminPasswordResult.stdout

- name: Install Plugins
  jenkins_plugin:
    name: "{{ item }}"
    # state: latest
    # url_username: admin
    # url_password: "{{ adminPasswordResult.stdout }}"
  with_items: 
    - script-security
    - command-launcher
    - blueocean

- name: Restart Jenkins Service
  service:
    name: jenkins
    state: restarted

- name: Sleep for 30 seconds and continue with play ...
  wait_for: timeout=30
  delegate_to: localhost