---
- name: Installing Java
  include_tasks: install_java.yml

- name: Installing Jenkins
  include_tasks: install_jenkins.yml

- name: Get Jenkins Init Admin Password
  include_tasks: get_init_admin_password.yml

- name: Configuring Jenkins
  include_tasks: initial_setting.yml

- name: Installing Jenkins Plugins
  include_tasks: install_plugins.yml