---
- name: Create Container in Proxmox and Host in AWX
  become: true
  become_method: sudo
  gather_facts: true
  hosts: "{{ host }}"
  roles:
    - role: common

  pre_tasks:
    - include_role:
        name: awx
        tasks_from: "collect_awx_token.yml"

    - include_role:
        name: proxmox
        tasks_from: "retrieve_last_ct_vm_info.yml"
        apply:
          delegate_to: proxmox

    - set_fact: 
        _network_ip: "{{ proxmox_next_container_ip }}"
        
  tasks:
    - include_role:
        name: proxmox
        tasks_from: "create_container.yml"
        apply:
          delegate_to: proxmox
          delegate_facts: true

    - include_role:
        name: awx
        tasks_from: "create_host.yml"