# ---
# - name: Create Container in Proxmox and Host in AWX
#   become: true
#   # become_method: sudo
#   gather_facts: true
#   hosts: "{{ host }}"
#   roles:
#     - role: common

#   pre_tasks:
#     - include_role:
#         name: awx
#         tasks_from: "collect_awx_token.yml"
#         apply:
#           delegate_to: ct-awx

#     - include_role:
#         name: proxmox
#         tasks_from: "retrieve_last_ct_vm_info.yml"

#     - set_fact: 
#         _network_ip: "{{ proxmox_next_container_ip }}"
#         _vmid: "{{ proxmox_next_container_id }}"
        
#   tasks:
#     - include_role:
#         name: proxmox
#         tasks_from: "create_container.yml"

#     - include_role:
#         name: awx
#         tasks_from: "create_host.yml"
#         apply:
#           delegate_to: ct-awx
#       vars:
#         external_call_host: "ct-awx"
    
#     - include_role:
#         name: common
#         tasks_from: "install-sshd-centos8stream.yml"
    
#     - include_role:
#         name: common
#         tasks_from: "update_operation-system.yml"
#         apply:
#           delegate_to: "{{ _hostname }}"
    
#     - include_role:
#         name: common
#         tasks_from: "install_oh-my-zsh.yml"
#         apply:
#           delegate_to: "{{ _hostname }}"





---
- name: Create Container in Proxmox and Host in AWX
  become: true
  # become_method: sudo
  # gather_facts: true
  hosts: "{{ host }}"

  tasks:
  - set_fact:
      password: hunter2

# - import_playbook: ../proxmox/create_container.yml

- name: ZZZZZZZ
  become: true
  # become_method: sudo
  # gather_facts: true
  hosts: ct-awx

  # tasks:
  # - set_fact:
  #     host: ct-awx

- import_playbook: create_host.yml
  vars:
    host: ct-awx


