---
- name: Delete Host in Ansible AWX
  become: true
  become_method: sudo
  gather_facts: true
  hosts: "{{ host }}"  
  roles:
    - role: common

  pre_tasks:
    - include_role:
        name: awx
        tasks_from: "collect_awx_token.yml"
        
  tasks:
    - include_role:
        name: awx
        tasks_from: "delete_host.yml"
        apply:
          delegate_to: ct-awx