---
- name: Destroy Container with VMID {{ _vmid }}
  become: true
  become_method: sudo
  gather_facts: true
  hosts: "{{ host }}"
  roles:
    - role: common

  pre_tasks:
    - include_role:
        name: awx
        tasks_from: "collect_awx_token.yml"
        apply:
          delegate_to: ct-awx
    
    - set_fact: 
        id: "{{ _vmid }}"
        _hostname: "{{ proxmox_vmid_name }}"

    - include_role:
        name: proxmox
        tasks_from: "get_informations_id.yml"

        
  tasks:
    - include_role:
        name: proxmox
        tasks_from: "destroy_container.yml"

    - name: Waiting 15 Seconds ...
      ansible.builtin.pause:
        seconds: 15

    - name: Delete host in known_hosts file
      delegate_to: ct-awx
      command: |
        docker exec awx_task /bin/bash -c 'sed -i "/{{ proxmox_vmid_ip }}/d" /root/.ssh/known_hosts'
      retries: 10
      delay: 10

    - include_role:
        name: awx
        tasks_from: "disable_host.yml"
        apply:
          delegate_to: ct-awx
      vars:
        external_call_host: "ct-awx"