---
- name: Copy Nginx Configuration Template
  copy:
    src: nginx.conf.template
    dest: /etc/nginx/nginx.conf.template

- name: Copy 404 Error Page
  copy:
    src: errorPages/404.html
    dest: /usr/share/nginx/html

- name: Copy 50x Error Page
  copy:
    src: errorPages/50x.html
    dest: /usr/share/nginx/html