---
- name: Destroy Host in Ansible AWX
  become: yes
  gather_facts: No
  hosts: "{{ host }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
  collections:
    - awx.awx

  tasks:
    - name: Collect AWX root token
      command: |
        docker exec awx_task /bin/bash -c 'awx-manage create_oauth2_token --user root'
      register: awx_token

    # - name: Disable host in inventory
    #   host:
    #     name: "{{ _hostname }}"
    #     inventory: "{{ _inventory }}"
    #     enabled: false
    #     controller_host: "http://{{ hostvars[host].ansible_host }}"
    #     controller_oauthtoken: "{{ awx_token.stdout }}"
    #     validate_certs: false

    # - name: Destroy host in inventory
    #   host:
    #     name: "{{ _hostname }}"
    #     inventory: "{{ _inventory }}"
    #     state: absent
    #     controller_host: "http://{{ hostvars[host].ansible_host }}"
    #     controller_oauthtoken: "{{ awx_token.stdout }}"
    #     validate_certs: false
    - name: Destroy host in inventory
      host:
        name: "{{ _hostname }}"
        inventory: "{{ _inventory }}"
        state: absent
