---
- name: Install Portainer Agent
  become: yes
  gather_facts: No
  hosts: "{{ HOSTS }}"

  tasks:
    # - name: Install requests python package
    #   pip:
    #     name: requests
    #   vars:
    #     ansible_python_interpreter: /bin/python3

    # - name: Creating Portainer Agent
    #   docker_container:
    #     name: portainer_agent
    #     image: portainer/agent:2.16.0
    #     state: started
    #     restart_policy: always
    #     volumes:
    #       - /var/run/docker.sock:/var/run/docker.sock
    #       - /var/lib/docker/volumes:/var/lib/docker/volumes
    #     ports:
    #       - "9001:9001"
    #   vars:
    #     ansible_python_interpreter: /bin/python3

    - name: Creating Portainer Agent
      register: portainer_agent
      ignore_errors: yes
      command: docker run -d -p 9001:9001 --name portainer_agent --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker/volumes:/var/lib/docker/volumes portainer/agent:2.16.0
