---
- name: Install Docker - CentOS 7
  gather_facts: No
  hosts: "{{ HOSTS }}"

  tasks:
    - name: Installing required packages
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: latest

    - name: Add Docker repository
      yum_repository:
        name: docker-ce
        description: Configuring the Docker repository
        baseurl: https://download.docker.com/linux/centos/docker-ce.repo

    - name: Installing Docker Engine
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest

    - name: Activating and starting the docker service
      service:
        name: docker
        state: started
        enabled: yes
