---
- name: Install SSHD
  become: yes
  gather_facts: No
  hosts: "{{ HOSTS }}"

  tasks:
    - name: Install the OpenSSH server package
      yum:
        name: openssh-server
        state: latest

    - name: Start the OpenSSH service
      service:
        name: sshd
        state: started
        enabled: yes

    - name:
      firewalld:
        zone: public
        permanent: yes
        service: ssh
        state: enabled

    - name: Reboot when packages were updated
      reboot:
