---
- name: Install Portainer Agent
  become: yes
  gather_facts: No
  hosts: "{{ HOSTS }}"

  tasks:
    - name: Creating Portainer Agent
      docker_container:
        name: portainer-agent
        image: portainer/agent:2.16.0
        restart: yes
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/lib/docker/volumes:/var/lib/docker/volumes
        ports:
          - "9001:9001"
