---
- name: Install SSHD
  become: yes
  gather_facts: No
  # hosts: "{{ host }}"
  hosts: proxmox
  vars:
    ansible_python_interpreter: /usr/bin/python3
  collections:
    - ansible.posix

  tasks:
    # - name: Install the OpenSSH server package
    #   package:
    #     name: openssh-server
    #     state: latest

    # - name: Start the OpenSSH service
    #   service:
    #     name: sshd
    #     state: started
    #     enabled: yes

    # - name:
    #   firewalld:
    #     zone: public
    #     permanent: yes
    #     service: ssh
    #     state: enabled

    # - name: Reboot when packages were updated
    #   reboot:

    - name: Teste Command
      command: |
        hostname
      register: output1

    - name: Teste connect lxc
      command: |
        lxc-attach --name 300
        hostname
      register: output2

    - name: Print the gateway for each host when defined
      debug:
        msg: O hostname é - {{ output1.stdout }}
    - name: Print 2
      debug:
        msg: Saida do lxc attach - {{ output2.stdout }}
