---
- name: Install SSHD
  become: yes
  gather_facts: No
  # hosts: "{{ host }}"
  hosts: proxmox
  vars:
    ansible_python_interpreter: /usr/bin/python3
  collections:
    - ansible.posix
    - community.general

  tasks:
    # - name: Install the OpenSSH server package
    #   package:
    #     name: openssh-server
    #     state: latest

    # - name: Start the OpenSSH service
    #   service:
    #     name: sshd
    #     state: started
    #     enabled: yes

    # - name:
    #   firewalld:
    #     zone: public
    #     permanent: yes
    #     service: ssh
    #     state: enabled

    # - name: Reboot when packages were updated
    #   reboot:

    # - name: Teste Command
    #   command: |
    #     hostname
    #   register: output1
    # - debug:
    #     msg: O hostname é - {{ output1.stdout }}

    # - name: Install sshd service
    #   command: |
    #     lxc-attach --name 300
    #     "yum install -y openssh-server"
    #   register: sshdinstall
    #   loop_control:
    #     pause: 5
    # - debug:
    #     msg: Install sshd service - {{ sshdinstall.stdout }}

    # - name: Teste connect lxc
    #   command: |
    #     lxc-attach --name 300
    #     systemctl status sshd
    #   register: output2
    # - debug:
    #     msg: SSHD status - {{ output2.stdout }}

    # - name: Print the gateway for each host when defined
    #   debug:
    #     msg: O hostname é - {{ output1.stdout }}
    # - name: Print 2
    #   debug:
    #     msg: Saida do lxc attach - {{ output2.stdout }}

    # - name: Install provisioning dependencies
    #   apt: name=lxc
    - name: Install python3 and python3-pip package
      package:
        name:
          - lxc
          - python3
          - python3-lxc
        state: present

    - name: Run a complex command within a "running" container
      # become: yes
      # connection: local
      lxc_container:
        # name: ct-tst
        name: 259
        container_command: |
          hostname

# apt-get update
# apt-get install -y curl wget vim apache2
# echo 'hello world.' | tee /opt/started
# if [[ -f "/opt/started" ]]; then
#     echo 'hello world.' | tee /opt/found-started
# fi

