---
- name: Install Jenkins
  become: true
  become_method: sudo
  gather_facts: true
  hosts: "{{ host }}"
  roles:
    - role: os_release
      vars:
        os_requirement_distribution: 'CentOS'
        os_requirement_version: "8" 
    - role: jenkins