---
- name: Install Jenkins
  become: true
  become_method: sudo
  gather_facts: true
  hosts: "{{ host }}"
  roles:
    # - role: "package_installed"
    # - role: "os_release"
    # - role: "machine_info"
    - { role: os_release, os_requirement_distribution: 'CentOS', os_requirement_version: "8" }
    - role: "jenkins"

  tasks: