---
- name: Destroy the Container with VMID {{ _vmid }} in the proxmox {{ _api_host }} Host
  become: yes
  gather_facts: No
  hosts: "{{ host }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Remove container
      proxmox:
        vmid: "{{ _vmid }}"
        api_user: "{{ _api_user }}"
        api_password: "{{ hostvars[host].ansible_password }}"
        api_host: "{{ _api_host }}"
        state: absent
