---
- name: Create new LXC container in Proxmox Cygnus Host
  become: yes
  gather_facts: No
  hosts: "{{ HOSTS }}"

  tasks:
    # - name: Add EPEL repository
    #   package:
    #     name: epel-release
    #     state: latest

    - name: Create new container with minimal options
      community.general.proxmox:
        vmid: 220
        node: pimentel-homelab
        api_user: root@pam
        api_password: 1q2w3e
        api_host: node1
        password: 123456
        hostname: example.org
        ostemplate: 'local:vztmpl/debian-11-turnkey-core_17.1-1_amd64.tar.gz
