---
- name: Create new LXC container in Proxmox [{{ _node }}]
  become: yes
  gather_facts: No
  hosts: "{{ host }}"
  # vars:
  #   ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: "Create Container"
      # proxmox:
      community.general.proxmox:
        vmid: "{{ _vmid }}" # Specifying Container ID
        node: "{{ _node }}" # Name of Proxmox host
        api_user: "{{ _api_user }}" # Proxmox user
        api_password: "{{ hostvars[host].ansible_password }}" # Password in plaintext !!!
        api_host: "{{ _api_host }}" # Proxmox hostname
        state: "{{ _state }}"
        hostname: "{{ _container_hostname }}" # Container hostname
        password: "{{ _container_password  }}" # Password in plaintext !!!
        ostemplate: "{{ _ostemplate }}" # Or use local:vztmpl/... as discussed
        cores: "{{ _cores }}"
        disk: "{{ _disk }}"
        memory: "{{ _memory }}"
        swap: "{{ _memory }}"
        storage: "local-lvm" # Or use 'local' as discussed
        netif: '{"net0":"name=eth0,gw={{ _network_gw }},ip={{ _network_ip }}/24,bridge=vmbr0"}'
        unprivileged: yes
        onboot: "{{ _onboot }}"
        description: "teste descrição"
        features:
          - nesting="{{ _nesting }}"
          - keyctl="{{ _keyctl }}"
      register: create_container_output
