---
- name: Playbook de Testes
  become: true
  become_method: sudo
  gather_facts: true
  # hosts: "{{ host }}"
  hosts: ct-awx
  vars:
    ansible_python_interpreter: /usr/bin/python3
  # collections:
  #   - awx.awx
  roles:
    # - role: "package_installed"
    # - role: "os_release"
    # - role: "machine_info"
    # - { role: package_installed, packages: [java] }
    # - { role: package_installed, packages: "{{pkgss}}" }
    # - { role: os_release, os_requirement_distribution: 'CentOS', os_requirement_version: "8" }
    - role: awx
      vars:
        awx_execution_mode: "delete_host"

        _hostname: teste
        _inventory: pimentel-inventory
        _awx_host: "ct-awx"
        _node: pimentel-homelab
        _api_host: pimentel-homelab
        _api_user: root@pam
    # - role: proxmox
    #   vars:
    #     proxmox_execution_mode: "ct_destroy"

  tasks:
    - name: XXXXXXXXXXXXXXXXXXXXXXX
      ansible.builtin.debug:
        msg:
        - "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY"