---
- name: Playbook de Testes
  become: true
  # become_method: sudo
  become_user: root
  gather_facts: true
  hosts: "{{ host }}"
  roles:
    - role: "package_installed"
    - role: "os_release"

  tasks:
    - name: Distribution X
      debug: msg="{{ ansible_distribution }}"
    - name: Distribution version X
      debug: msg="{{ ansible_distribution_version}}"
    - name: Distribution major version X
      debug: msg="{{ ansible_distribution_major_version }}"