---
- name: Playbook de Testes
  become: true
  become_method: sudo
  gather_facts: false
  hosts: "{{ host }}"

  tasks:
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Print the package facts
      ansible.builtin.debug:
        var: ansible_facts.packages

    - name: Check whether a package called {{ app }} is installed
      ansible.builtin.debug:
        msg: "{{ ansible_facts.packages['{{ app }}'] | length }} versions of {{ app }} are installed!"
      when: "'{{ app }}' in ansible_facts.packages"