---
- name: Playbook de Testes
  become: true
  # become_method: sudo
  become_user: root
  gather_facts: true
  hosts: "{{ host }}"
  roles:
    - role: "check_package_installed"

  tasks:
    - name: Distribution
      debug: msg="{{ ansible_distribution }}"
    - name: Distribution version
      debug: msg="{{ ansible_distribution_version}}"
    - name: Distribution major version
      debug: msg="{{ ansible_distribution_major_version }}"