---
- name: Playbook de Testes
  become: true
  become_method: sudo
  gather_facts: true
  hosts: "{{ host }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
  # collections:
  #   - awx.awx
  roles:
    # - role: "package_installed"
    # - role: "machine_info"
    # - { role: package_installed, packages: [proxmoxer] }
    # - { role: package_installed, packages: "{{pkgss}}" }
    # - role: os_release
    #   vars:
    #     os_requirement_distribution: 'CentOS'
    #     os_requirement_version: "8"
    #   tags: [os_verify]
    # - role: proxmox
    #   vars:
    #     proxmox_execution_mode: "ct_destroy"
    # - role: awx
    #   vars:
    #     awx_execution_mode: "disable_host"

    #     _inventory: pimentel-inventory
    #     _id: 204

  tasks:
    - name: XXXXXXXXXXXXXXXXXXXXXXX
      ansible.builtin.debug:
        msg:
        - "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY"

    - name: Include the example role
      include_role:
        name: os_release
      vars:
        os_requirement_distribution: 'CentOS'
        os_requirement_version: "8"
      # tags: os_verify