---
- name: Playbook de Testes
  become: true
  become_method: sudo
  gather_facts: true
  hosts: "{{ host }}"
  # vars:
  #   ansible_python_interpreter: /usr/bin/python3
  # collections:
  #   - awx.awx
  roles:
    - role: common
    # - role: "package_installed"
    # - role: "machine_info"
    # - { role: package_installed, packages: [proxmoxer] }
    # - { role: package_installed, packages: "{{pkgss}}" }
    # - role: os_release
    #   # tasks_from: "verify_os.yml"
    #   tasks_from: "check.yml"
    #   vars:
    #     os_requirement_distribution: 'CentOS'
    #     os_requirement_version: "8"
      # tags: [ os_verify ]
    # - role: proxmox
    #   vars:
    #     proxmox_execution_mode: "ct_destroy"
    # - role: awx
    #   vars:
    #     awx_execution_mode: "disable_host"

    #     _inventory: pimentel-inventory
    #     _id: 204

  tasks:


    - include_role:
        delegate_to: proxmox
        name: proxmox
        tasks_from: "get_informations.yml"
      # vars:
      #   os_requirement_distribution: 'CentOS'
      #   os_requirement_version: "8"
    
    # - include_role:
    #     name: jenkins



    - name: XXXXXXXXXXXXXXXXXXXXXXX
      ansible.builtin.debug:
        msg:
        - "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY"

    - name: UUUUUUUUUUUUUUUUUUUUU
      debug: msg="ZZZZ:{{ teste_rap }}"

    - name: vmid/ctid hostname and ip
      debug: msg="Hostname:{{ result_hostname.stdout }} | Ip:{{ result_ip.stdout }}"