---
- name: Playbook de Testes
  become: true
  become_method: sudo
  gather_facts: true
  hosts: "{{ host }}"
  roles:
    - role: "package_installed"
    - role: "os_release"

  # tasks:
  #   - name: Gather the package facts
  #     ansible.builtin.package_facts:
  #       manager: auto

  #   - name: Print the package facts
  #     ansible.builtin.debug:
  #       var: ansible_facts.packages

  #   - name: Check whether a package called {{ app }} is installed
  #     ansible.builtin.debug:
  #       # msg: "{{ ansible_facts.packages['{{ app }}'] | length }} versions of {{ app }} are installed!"
  #       msg: "AAAAAAAAAA"
  #     when: '"{{ app }}" in ansible_facts.packages'
    
  #   - name: Check whether a package called {{ app2 }} is installed
  #     ansible.builtin.debug:
  #       # msg: "{{ ansible_facts.packages['{{ app }}'] | length }} versions of {{ app }} are installed!"
  #       msg: "BBBBBBBBBB"
  #     when: '"{{ app2 }}" in ansible_facts.packages'

  #   - name: Package status
  #     debug:
  #       msg: "{{ item }} {{ 'installed' if item in ansible_facts.packages else 'not installed' }}"
  #     loop: "{{ pkgs | default([]) }}"


  tasks:
    - name: Distribution X
      debug: msg="{{ ansible_distribution }} == {{ ansible_distribution_version}}"
    - name: Distribution version X
      debug: msg="{{ ansible_distribution_version}}"
    - name: Distribution major version X
      debug: msg="{{ ansible_distribution_major_version }}"
    
    
    
    - name: VVVVVVVV
      ansible.builtin.debug: 
        msg: "É CentOs .............."
      when: ansible_distribution == "CentOS"
    
    - name: YYYYYYYYYY
      ansible.builtin.debug: 
        msg: "Não É CentOs .............."
      when: ansible_distribution == "Debian"