---
- name: Update CentOS 7
  become: yes
  gather_facts: No
  hosts: "{{ HOSTS }}"

  tasks:
    - name: Add EPEL repository
      yum:
        name: epel-release
        state: latest

    - name: Update the system package repository cache
      command: yum -y makecache

    - name: Update the system packages
      yum:
        name: "*"
        state: latest
        update_cache: yes
        update_only: yes

    - name: Remove packages not needed anymore
      yum:
        autoremove: yes

    - name: Install common packages
      yum:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest

    - name: Reboot System
      reboot:
