---
- name: Update CentOS 7
  become: yes
  gather_facts: No
  hosts: "{{ HOSTS }}"

  tasks:
    - name: Add EPEL repository
      package:
        name: epel-release
        state: latest

    - name: Update the system package repository cache
      command: yum -y makecache

    - name: Update the system packages
      package:
        name: "*"
        state: latest

    - name: Remove packages not needed anymore
      package:
        autoremove: yes

    - name: Install common packages
      package:
        name:
          - ca-certificates
          - curl
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
      ignore_errors: yes

    - name: Reboot System
      reboot:
