---
- name: Update System
  become: yes
  gather_facts: No
  hosts: "{{ host_update_so }}"

  tasks:
    - name: Add EPEL repository
      package:
        name: epel-release
        state: latest

    - name: Update the system packages
      package:
        name: "*"
        state: latest

    - name: Remove packages not needed anymore
      package:
        autoremove: yes

    - name: Install common packages
      package:
        name:
          - ca-certificates
          - curl
          - wget
          - python3-pip
          - python3-setuptools
          - nano
          - tar
          - util-linux-user
          - git
          - qemu-guest-agent
        state: latest
      ignore_errors: yes

    - name: Start qemu-guest-agent Service
      service:
        name: qemu-guest-agent
        state: started
        enabled: yes

    - name: Reboot System
      reboot:
