---
- name: Update CentOS 7
  gather_facts: No
  hosts: "{{ HOSTS }}"

  tasks:
    - name: Adding EPEL repository
      yum:
        name: epel-release
        state: latest

    - name: Updating the system package repository cache
      command: yum -y makecache
      warn: false

    - name: Updating the system packages
      yum:
        name: "*"
        state: latest
        update_cache: yes
        update_only: yes

    - name: Remove packages not needed anymore
      yum:
        autoremove: yes

    - name: Reboot when packages were updated
      reboot:
